// trainer.proto
//
// This file defines the gRPC communication protocol between Master and Workers.
//
// HOW gRPC WORKS:
// ────────────────
// gRPC uses Protocol Buffers (protobuf) to define:
//   1. Services  → What functions can be called remotely (like an API)
//   2. Messages  → What data is sent/received (like JSON but binary & faster)
//
// The `protoc` compiler reads this file and generates Go code that handles
// all the networking, serialization, and deserialization automatically.
//
// ARCHITECTURE:
// ────────────────
//   Worker ──── gRPC ────► Master
//
//   Workers CALL these methods on the master:
//     RegisterWorker  → "Hey master, I'm alive, add me to the cluster"
//     SendHeartbeat   → "I'm still alive" (every 5 seconds)
//     SendGradients   → "Here are my computed gradients from training"
//     GetWeights      → "Give me the latest model weights"

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/trainer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrainerService_RegisterWorker_FullMethodName = "/trainer.TrainerService/RegisterWorker"
	TrainerService_SendHeartbeat_FullMethodName  = "/trainer.TrainerService/SendHeartbeat"
	TrainerService_SendGradients_FullMethodName  = "/trainer.TrainerService/SendGradients"
	TrainerService_GetWeights_FullMethodName     = "/trainer.TrainerService/GetWeights"
	TrainerService_GetTask_FullMethodName        = "/trainer.TrainerService/GetTask"
	TrainerService_SaveCheckpoint_FullMethodName = "/trainer.TrainerService/SaveCheckpoint"
)

// TrainerServiceClient is the client API for TrainerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrainerServiceClient interface {
	// Worker calls this ONCE at startup to join the cluster
	RegisterWorker(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Worker calls this every 5 seconds so master knows it's alive
	SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Worker sends computed gradients after training a batch
	SendGradients(ctx context.Context, in *GradientRequest, opts ...grpc.CallOption) (*GradientResponse, error)
	// Worker requests latest model weights from master
	GetWeights(ctx context.Context, in *WeightsRequest, opts ...grpc.CallOption) (*WeightsResponse, error)
	// Master assigns a training task (data shard) to a worker
	// Worker calls this to poll for new tasks
	GetTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	// Master saves/loads model checkpoints
	SaveCheckpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error)
}

type trainerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrainerServiceClient(cc grpc.ClientConnInterface) TrainerServiceClient {
	return &trainerServiceClient{cc}
}

func (c *trainerServiceClient) RegisterWorker(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, TrainerService_RegisterWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainerServiceClient) SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, TrainerService_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainerServiceClient) SendGradients(ctx context.Context, in *GradientRequest, opts ...grpc.CallOption) (*GradientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GradientResponse)
	err := c.cc.Invoke(ctx, TrainerService_SendGradients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainerServiceClient) GetWeights(ctx context.Context, in *WeightsRequest, opts ...grpc.CallOption) (*WeightsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WeightsResponse)
	err := c.cc.Invoke(ctx, TrainerService_GetWeights_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainerServiceClient) GetTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, TrainerService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainerServiceClient) SaveCheckpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointResponse)
	err := c.cc.Invoke(ctx, TrainerService_SaveCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrainerServiceServer is the server API for TrainerService service.
// All implementations must embed UnimplementedTrainerServiceServer
// for forward compatibility.
type TrainerServiceServer interface {
	// Worker calls this ONCE at startup to join the cluster
	RegisterWorker(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Worker calls this every 5 seconds so master knows it's alive
	SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Worker sends computed gradients after training a batch
	SendGradients(context.Context, *GradientRequest) (*GradientResponse, error)
	// Worker requests latest model weights from master
	GetWeights(context.Context, *WeightsRequest) (*WeightsResponse, error)
	// Master assigns a training task (data shard) to a worker
	// Worker calls this to poll for new tasks
	GetTask(context.Context, *TaskRequest) (*TaskResponse, error)
	// Master saves/loads model checkpoints
	SaveCheckpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error)
	mustEmbedUnimplementedTrainerServiceServer()
}

// UnimplementedTrainerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrainerServiceServer struct{}

func (UnimplementedTrainerServiceServer) RegisterWorker(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedTrainerServiceServer) SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedTrainerServiceServer) SendGradients(context.Context, *GradientRequest) (*GradientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendGradients not implemented")
}
func (UnimplementedTrainerServiceServer) GetWeights(context.Context, *WeightsRequest) (*WeightsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWeights not implemented")
}
func (UnimplementedTrainerServiceServer) GetTask(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedTrainerServiceServer) SaveCheckpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveCheckpoint not implemented")
}
func (UnimplementedTrainerServiceServer) mustEmbedUnimplementedTrainerServiceServer() {}
func (UnimplementedTrainerServiceServer) testEmbeddedByValue()                        {}

// UnsafeTrainerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrainerServiceServer will
// result in compilation errors.
type UnsafeTrainerServiceServer interface {
	mustEmbedUnimplementedTrainerServiceServer()
}

func RegisterTrainerServiceServer(s grpc.ServiceRegistrar, srv TrainerServiceServer) {
	// If the following call panics, it indicates UnimplementedTrainerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrainerService_ServiceDesc, srv)
}

func _TrainerService_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainerServiceServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainerService_RegisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainerServiceServer).RegisterWorker(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainerService_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainerServiceServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainerService_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainerServiceServer).SendHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainerService_SendGradients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainerServiceServer).SendGradients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainerService_SendGradients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainerServiceServer).SendGradients(ctx, req.(*GradientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainerService_GetWeights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainerServiceServer).GetWeights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainerService_GetWeights_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainerServiceServer).GetWeights(ctx, req.(*WeightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainerService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainerServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainerService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainerServiceServer).GetTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainerService_SaveCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainerServiceServer).SaveCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainerService_SaveCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainerServiceServer).SaveCheckpoint(ctx, req.(*CheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrainerService_ServiceDesc is the grpc.ServiceDesc for TrainerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrainerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trainer.TrainerService",
	HandlerType: (*TrainerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorker",
			Handler:    _TrainerService_RegisterWorker_Handler,
		},
		{
			MethodName: "SendHeartbeat",
			Handler:    _TrainerService_SendHeartbeat_Handler,
		},
		{
			MethodName: "SendGradients",
			Handler:    _TrainerService_SendGradients_Handler,
		},
		{
			MethodName: "GetWeights",
			Handler:    _TrainerService_GetWeights_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _TrainerService_GetTask_Handler,
		},
		{
			MethodName: "SaveCheckpoint",
			Handler:    _TrainerService_SaveCheckpoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/trainer.proto",
}
