// trainer.proto
//
// This file defines the gRPC communication protocol between Master and Workers.
//
// HOW gRPC WORKS:
// ────────────────
// gRPC uses Protocol Buffers (protobuf) to define:
//   1. Services  → What functions can be called remotely (like an API)
//   2. Messages  → What data is sent/received (like JSON but binary & faster)
//
// The `protoc` compiler reads this file and generates Go code that handles
// all the networking, serialization, and deserialization automatically.
//
// ARCHITECTURE:
// ────────────────
//   Worker ──── gRPC ────► Master
//
//   Workers CALL these methods on the master:
//     RegisterWorker  → "Hey master, I'm alive, add me to the cluster"
//     SendHeartbeat   → "I'm still alive" (every 5 seconds)
//     SendGradients   → "Here are my computed gradients from training"
//     GetWeights      → "Give me the latest model weights"

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/trainer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"` // Unique ID like "worker1", "worker2"
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`                   // IP/hostname of the worker
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_trainer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trainer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_trainer_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "registered" if successful
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_trainer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trainer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_trainer_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"` // Which worker is sending the heartbeat
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_trainer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trainer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_trainer_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "alive" acknowledgment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_trainer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trainer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_trainer_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GradientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"` // Which worker computed these gradients
	Gradients     []float32              `protobuf:"fixed32,2,rep,packed,name=gradients,proto3" json:"gradients,omitempty"`      // The gradient vector (list of floats)
	Loss          float64                `protobuf:"fixed64,3,opt,name=loss,proto3" json:"loss,omitempty"`                       // Training loss for this worker's batch (master averages across workers)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradientRequest) Reset() {
	*x = GradientRequest{}
	mi := &file_proto_trainer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradientRequest) ProtoMessage() {}

func (x *GradientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trainer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradientRequest.ProtoReflect.Descriptor instead.
func (*GradientRequest) Descriptor() ([]byte, []int) {
	return file_proto_trainer_proto_rawDescGZIP(), []int{4}
}

func (x *GradientRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *GradientRequest) GetGradients() []float32 {
	if x != nil {
		return x.Gradients
	}
	return nil
}

func (x *GradientRequest) GetLoss() float64 {
	if x != nil {
		return x.Loss
	}
	return 0
}

type GradientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "received" acknowledgment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradientResponse) Reset() {
	*x = GradientResponse{}
	mi := &file_proto_trainer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradientResponse) ProtoMessage() {}

func (x *GradientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trainer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradientResponse.ProtoReflect.Descriptor instead.
func (*GradientResponse) Descriptor() ([]byte, []int) {
	return file_proto_trainer_proto_rawDescGZIP(), []int{5}
}

func (x *GradientResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type WeightsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeightsRequest) Reset() {
	*x = WeightsRequest{}
	mi := &file_proto_trainer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightsRequest) ProtoMessage() {}

func (x *WeightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trainer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightsRequest.ProtoReflect.Descriptor instead.
func (*WeightsRequest) Descriptor() ([]byte, []int) {
	return file_proto_trainer_proto_rawDescGZIP(), []int{6}
}

type WeightsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weights       []float32              `protobuf:"fixed32,1,rep,packed,name=weights,proto3" json:"weights,omitempty"` // The full model weight vector
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeightsResponse) Reset() {
	*x = WeightsResponse{}
	mi := &file_proto_trainer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightsResponse) ProtoMessage() {}

func (x *WeightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trainer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightsResponse.ProtoReflect.Descriptor instead.
func (*WeightsResponse) Descriptor() ([]byte, []int) {
	return file_proto_trainer_proto_rawDescGZIP(), []int{7}
}

func (x *WeightsResponse) GetWeights() []float32 {
	if x != nil {
		return x.Weights
	}
	return nil
}

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"` // Which worker is asking for a task
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_trainer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trainer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_trainer_proto_rawDescGZIP(), []int{8}
}

func (x *TaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardPath     string                 `protobuf:"bytes,1,opt,name=shard_path,json=shardPath,proto3" json:"shard_path,omitempty"`            // Path to the data shard file
	BatchSize     int32                  `protobuf:"varint,2,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`           // How many samples per training batch
	LearningRate  float32                `protobuf:"fixed32,3,opt,name=learning_rate,json=learningRate,proto3" json:"learning_rate,omitempty"` // Learning rate for gradient descent
	Epoch         int32                  `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`                                    // Current training epoch number
	HasTask       bool                   `protobuf:"varint,5,opt,name=has_task,json=hasTask,proto3" json:"has_task,omitempty"`                 // False if no task available (training done)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_proto_trainer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trainer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_trainer_proto_rawDescGZIP(), []int{9}
}

func (x *TaskResponse) GetShardPath() string {
	if x != nil {
		return x.ShardPath
	}
	return ""
}

func (x *TaskResponse) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *TaskResponse) GetLearningRate() float32 {
	if x != nil {
		return x.LearningRate
	}
	return 0
}

func (x *TaskResponse) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TaskResponse) GetHasTask() bool {
	if x != nil {
		return x.HasTask
	}
	return false
}

type CheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          int32                  `protobuf:"varint,1,opt,name=step,proto3" json:"step,omitempty"` // Training step number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointRequest) Reset() {
	*x = CheckpointRequest{}
	mi := &file_proto_trainer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointRequest) ProtoMessage() {}

func (x *CheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trainer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointRequest.ProtoReflect.Descriptor instead.
func (*CheckpointRequest) Descriptor() ([]byte, []int) {
	return file_proto_trainer_proto_rawDescGZIP(), []int{10}
}

func (x *CheckpointRequest) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

type CheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "saved" or error message
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`     // Where the checkpoint was saved
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointResponse) Reset() {
	*x = CheckpointResponse{}
	mi := &file_proto_trainer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointResponse) ProtoMessage() {}

func (x *CheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trainer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointResponse.ProtoReflect.Descriptor instead.
func (*CheckpointResponse) Descriptor() ([]byte, []int) {
	return file_proto_trainer_proto_rawDescGZIP(), []int{11}
}

func (x *CheckpointResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CheckpointResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_proto_trainer_proto protoreflect.FileDescriptor

const file_proto_trainer_proto_rawDesc = "" +
	"\n" +
	"\x13proto/trainer.proto\x12\atrainer\"H\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"*\n" +
	"\x10RegisterResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"/\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"+\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"`\n" +
	"\x0fGradientRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1c\n" +
	"\tgradients\x18\x02 \x03(\x02R\tgradients\x12\x12\n" +
	"\x04loss\x18\x03 \x01(\x01R\x04loss\"*\n" +
	"\x10GradientResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x10\n" +
	"\x0eWeightsRequest\"+\n" +
	"\x0fWeightsResponse\x12\x18\n" +
	"\aweights\x18\x01 \x03(\x02R\aweights\"*\n" +
	"\vTaskRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\xa2\x01\n" +
	"\fTaskResponse\x12\x1d\n" +
	"\n" +
	"shard_path\x18\x01 \x01(\tR\tshardPath\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x02 \x01(\x05R\tbatchSize\x12#\n" +
	"\rlearning_rate\x18\x03 \x01(\x02R\flearningRate\x12\x14\n" +
	"\x05epoch\x18\x04 \x01(\x05R\x05epoch\x12\x19\n" +
	"\bhas_task\x18\x05 \x01(\bR\ahasTask\"'\n" +
	"\x11CheckpointRequest\x12\x12\n" +
	"\x04step\x18\x01 \x01(\x05R\x04step\"@\n" +
	"\x12CheckpointResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path2\xa9\x03\n" +
	"\x0eTrainerService\x12E\n" +
	"\x0eRegisterWorker\x12\x18.trainer.RegisterRequest\x1a\x19.trainer.RegisterResponse\x12F\n" +
	"\rSendHeartbeat\x12\x19.trainer.HeartbeatRequest\x1a\x1a.trainer.HeartbeatResponse\x12D\n" +
	"\rSendGradients\x12\x18.trainer.GradientRequest\x1a\x19.trainer.GradientResponse\x12?\n" +
	"\n" +
	"GetWeights\x12\x17.trainer.WeightsRequest\x1a\x18.trainer.WeightsResponse\x126\n" +
	"\aGetTask\x12\x14.trainer.TaskRequest\x1a\x15.trainer.TaskResponse\x12I\n" +
	"\x0eSaveCheckpoint\x12\x1a.trainer.CheckpointRequest\x1a\x1b.trainer.CheckpointResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_trainer_proto_rawDescOnce sync.Once
	file_proto_trainer_proto_rawDescData []byte
)

func file_proto_trainer_proto_rawDescGZIP() []byte {
	file_proto_trainer_proto_rawDescOnce.Do(func() {
		file_proto_trainer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_trainer_proto_rawDesc), len(file_proto_trainer_proto_rawDesc)))
	})
	return file_proto_trainer_proto_rawDescData
}

var file_proto_trainer_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_trainer_proto_goTypes = []any{
	(*RegisterRequest)(nil),    // 0: trainer.RegisterRequest
	(*RegisterResponse)(nil),   // 1: trainer.RegisterResponse
	(*HeartbeatRequest)(nil),   // 2: trainer.HeartbeatRequest
	(*HeartbeatResponse)(nil),  // 3: trainer.HeartbeatResponse
	(*GradientRequest)(nil),    // 4: trainer.GradientRequest
	(*GradientResponse)(nil),   // 5: trainer.GradientResponse
	(*WeightsRequest)(nil),     // 6: trainer.WeightsRequest
	(*WeightsResponse)(nil),    // 7: trainer.WeightsResponse
	(*TaskRequest)(nil),        // 8: trainer.TaskRequest
	(*TaskResponse)(nil),       // 9: trainer.TaskResponse
	(*CheckpointRequest)(nil),  // 10: trainer.CheckpointRequest
	(*CheckpointResponse)(nil), // 11: trainer.CheckpointResponse
}
var file_proto_trainer_proto_depIdxs = []int32{
	0,  // 0: trainer.TrainerService.RegisterWorker:input_type -> trainer.RegisterRequest
	2,  // 1: trainer.TrainerService.SendHeartbeat:input_type -> trainer.HeartbeatRequest
	4,  // 2: trainer.TrainerService.SendGradients:input_type -> trainer.GradientRequest
	6,  // 3: trainer.TrainerService.GetWeights:input_type -> trainer.WeightsRequest
	8,  // 4: trainer.TrainerService.GetTask:input_type -> trainer.TaskRequest
	10, // 5: trainer.TrainerService.SaveCheckpoint:input_type -> trainer.CheckpointRequest
	1,  // 6: trainer.TrainerService.RegisterWorker:output_type -> trainer.RegisterResponse
	3,  // 7: trainer.TrainerService.SendHeartbeat:output_type -> trainer.HeartbeatResponse
	5,  // 8: trainer.TrainerService.SendGradients:output_type -> trainer.GradientResponse
	7,  // 9: trainer.TrainerService.GetWeights:output_type -> trainer.WeightsResponse
	9,  // 10: trainer.TrainerService.GetTask:output_type -> trainer.TaskResponse
	11, // 11: trainer.TrainerService.SaveCheckpoint:output_type -> trainer.CheckpointResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_trainer_proto_init() }
func file_proto_trainer_proto_init() {
	if File_proto_trainer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_trainer_proto_rawDesc), len(file_proto_trainer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_trainer_proto_goTypes,
		DependencyIndexes: file_proto_trainer_proto_depIdxs,
		MessageInfos:      file_proto_trainer_proto_msgTypes,
	}.Build()
	File_proto_trainer_proto = out.File
	file_proto_trainer_proto_goTypes = nil
	file_proto_trainer_proto_depIdxs = nil
}
